'use client';
import './globals.css';
import {Inter} from 'next/font/google';
// redux
import {Provider} from 'react-redux';
import store from '../redux/store';
import store2 from '../redux02/store';

const inter = Inter({subsets: ['latin']});

store2.Subscribe(() => console.log(store2.getStore()));
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider store={store2}>{children}</Provider>
      </body>
    </html>
  );
}
